#!/bin/bash

months=(
    "January"   "February"  "March"     "April"
    "May"       "June"      "July"      "August"
    "September" "October"   "November"  "December"
)

for month in "${months[@]}"; do
    mkdir -p "$month"
done
